/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-06 16:45:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>JSP Page</title>\n");
      out.write("\n");
      out.write("    <!-- Compiled and minified CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css\">\n");
      out.write("\n");
      out.write("    <!-- Compiled and minified JavaScript -->\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js\"></script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body style=\"background: url(img/bg.jpg); background-size: cover; background-attachment: fixed;\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col m6 offset-m3\">\n");
      out.write("				<div class=\"card\">\n");
      out.write("					<div class=\"card-content\">\n");
      out.write("						<h3 style=\"margin-top: 10px;\" class=\"center-align\">Register Here!</h3>\n");
      out.write("						<h5 id=\"msg\" class=\"center-align\"></h5>\n");
      out.write("						\n");
      out.write("						<div class=\"form center-align\">\n");
      out.write("						\n");
      out.write("							<form action=\"Register\" method=\"post\" id=\"myform\">\n");
      out.write("								<input type=\"text\" name=\"user_name\" placeholder=\"Enter user name\" />\n");
      out.write("								<input type=\"password\" name=\"user_password\" placeholder=\"Enter user password\" />\n");
      out.write("								<input type=\"email\" name=\"user_email\" placeholder=\"Enter user email\" />\n");
      out.write("								\n");
      out.write("								<div class=\"file-field input-field\">\n");
      out.write("							      <div class=\"btn blue\">\n");
      out.write("							        <span>File</span>\n");
      out.write("							        <input name=\"image\" type=\"file\">\n");
      out.write("							      </div>\n");
      out.write("							      <div class=\"file-path-wrapper\">\n");
      out.write("							        <input class=\"file-path validate\" type=\"text\">\n");
      out.write("							      </div>\n");
      out.write("							    </div>\n");
      out.write("								\n");
      out.write("								<button type=\"submit\" class=\"btn light-blue accent-3\">Submit</button>\n");
      out.write("								\n");
      out.write("							</form>\n");
      out.write("						\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<div class=\"loader center-align\" style=\"margin-top: 10px; display: none;\">\n");
      out.write("						\n");
      out.write("						\n");
      out.write("    <div class=\"preloader-wrapper big active\">\n");
      out.write("      <div class=\"spinner-layer spinner-blue\">\n");
      out.write("        <div class=\"circle-clipper left\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"gap-patch\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"circle-clipper right\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"spinner-layer spinner-red\">\n");
      out.write("        <div class=\"circle-clipper left\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"gap-patch\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"circle-clipper right\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"spinner-layer spinner-yellow\">\n");
      out.write("        <div class=\"circle-clipper left\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"gap-patch\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"circle-clipper right\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"spinner-layer spinner-green\">\n");
      out.write("        <div class=\"circle-clipper left\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"gap-patch\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div><div class=\"circle-clipper right\">\n");
      out.write("          <div class=\"circle\"></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("						\n");
      out.write("						<h5>Please wait...</h5>\n");
      out.write("						\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<script\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\n");
      out.write("  integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\n");
      out.write("  crossorigin=\"anonymous\"></script>\n");
      out.write("  \n");
      out.write("  <script>\n");
      out.write("  	$(document).ready(function(){\n");
      out.write("  		// console.log(\"page is ready..\")\n");
      out.write("  		\n");
      out.write("  		$(\"#myform\").on('submit',function(event){\n");
      out.write("  			event.preventDefault();\n");
      out.write("  			\n");
      out.write("  			//var f =$(this).serialize();\n");
      out.write("  			\n");
      out.write("  			let f = new FormData(this);\n");
      out.write("  			\n");
      out.write("  			console.log(f);\n");
      out.write("  			\n");
      out.write("  			$(\".loader\").show();\n");
      out.write("  			$(\".form\").hide();\n");
      out.write("  			\n");
      out.write("  			$.ajax({\n");
      out.write("  				url: \"Register\",\n");
      out.write("  				data: f,\n");
      out.write("  				type: 'POST',\n");
      out.write("  				success: function(data, textStatus, jqXHR) {\n");
      out.write("  					console.log(data);\n");
      out.write("  					console.log(\"success....\")\n");
      out.write("  					\n");
      out.write("  					$(\".loader\").hide();\n");
      out.write("  		  			$(\".form\").show();\n");
      out.write("  		  			\n");
      out.write("  		  			if (data.trim() === 'done'){\n");
      out.write("  		  				$('#msg').html(\"Successfully Registered!\")\n");
      out.write("  		  				$('#msg').addClass('green-text')\n");
      out.write("  		  			}\n");
      out.write("  		  			else{\n");
      out.write("  		  				$('#msg').html(\"Something went wrong!\")\n");
      out.write("  		  				$('#msg').addClass('red-text')\n");
      out.write("  		  			}\n");
      out.write("  		  			\n");
      out.write("  					\n");
      out.write("  				},\n");
      out.write("  				error: function(jqXHR, textStatus, errorThrown) {\n");
      out.write("  					console.log(data);\n");
      out.write("  					console.log(\"error....\")\n");
      out.write("  					\n");
      out.write("  					$(\".loader\").hide();\n");
      out.write("  		  			$(\".form\").show();\n");
      out.write("  		  			$('#msg').html(\"Something went wrong!\")\n");
      out.write("  		  			$('#msg').addClass('red-text')\n");
      out.write("  					\n");
      out.write("  				},\n");
      out.write("  				processData: false,\n");
      out.write("  				contentType: false\n");
      out.write("  			})\n");
      out.write("  			\n");
      out.write("  		})\n");
      out.write("  		\n");
      out.write("  	})\n");
      out.write("  </script>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
